### ISSUE TITLE
Update to latest version of fs-extra

### ISSUE THREAD

**Issue by justinbmeyer** [jprichardson/node-github-download#10]
@jprichardson Any chance you can update this to the latest version of fs-extra.  Using this project on windows break's without it.

If you are busy, could you add me as a contributor and as an npm contributor and I'll do it.  Checkout my github profile, I'm pretty well versed in open source.

Thanks!

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-github-download/commit/07c3f8eaca4255f5dcc2b4de574c7f27aebfb901

Done. Let me know if you run into any issues.
